[build]
  publish = "public/"
  command = "yarn build"
  
[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"


[[redirects]]
  from = "/api"
  to = "https://en.wikiquote.org/w/api.php"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify", Access-Control-Allow-Origin = "*"}
